themesDir = 'themes/'

baseURL = 'https://artmakna.github.io/'
languageCode = 'ru-ru'
title = 'ЭТО ОЧЕРКИ'
theme = 'not-much-theme'
# publishdir = './public/'

[markup]
  [markup.highlight]
    style = 'dracula'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
theme = "auto"
palette = "eink"
showThemeNotice = true
showPostsSummary = true


[menu]
  [[menu.main]]
    identifier = "home"
    name = "home"
    title = "привет"
    url = "/"
    weight = 1
  
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "очерки"
    url = "/posts"
    weight = 2
